if(!MS.get(MS.key.auth,null))location.href='login.html';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);

function money(n){return MS.money(n)}
function goSection(id){$$('.admin-section').forEach(s=>s.classList.toggle('active',s.id===id));
    $$('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id));
    if($('#mobileNav'))$('#mobileNav').value=id;
    renderAll()}

$$('.side-nav button').forEach(b=>b.addEventListener('click',()=>goSection(b.dataset.section)));
$('#mobileNav')?.addEventListener('change',e=>goSection(e.target.value));
$('#logout')?.addEventListener('click',()=>{localStorage.removeItem(MS.key.auth);
    location.href='login.html'});
function totals(){const orders=MS.get(MS.key.orders,[]),
    offline=MS.get(MS.key.offline,[]),
    expenses=MS.get(MS.key.expenses,[]);
    
    const onlineRev=orders.filter(o=>o.status!=='Cancelled').reduce((s,o)=>s+o.total,0),
    offlineRev=offline.reduce((s,o)=>s+o.total,0),
    cogs=orders.filter(o=>o.status!=='Cancelled').reduce((s,o)=>s+o.items.reduce((x,i)=>x+i.cost*i.qty,0),0)+offline.reduce((s,o)=>s+o.cost*o.qty,0),
    exp=expenses.reduce((s,e)=>s+Number(e.amount),0);return{orders,
        offline,
        expenses,
        onlineRev,
        offlineRev,
        revenue:onlineRev+offlineRev,
        cogs,expensesTotal:exp,gross:onlineRev+offlineRev-cogs,
        net:onlineRev+offlineRev-cogs-exp}}
function renderOverview(){const t=totals(),ps=MS.get(MS.key.products,[]),low=ps.filter(p=>p.stock<=p.threshold&&p.stock>0).length,out=ps.filter(p=>p.stock===0).length;$('#stats').innerHTML=[['Revenue',money(t.revenue)],['Net Profit',money(t.net)],['Online Orders',t.orders.filter(o=>o.source==='Online').length],['Low Stock',low+out]].map(x=>`<div class="stat-card"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const key=`${d.getFullYear()}-${d.getMonth()}`;const val=[...t.orders.map(o=>({date:o.date,total:o.total})),...t.offline.map(o=>({date:o.date,total:o.total}))].filter(x=>{const z=new Date(x.date);return `${z.getFullYear()}-${z.getMonth()}`===key}).reduce((s,x)=>s+x.total,0);return{label:d.toLocaleString('en',{month:'short'}),value:val}});const max=Math.max(...months.map(x=>x.value),1);$('#salesChart').innerHTML=months.map(m=>`<div class="bar" style="height:${Math.max(8,m.value/max*190)}px"><span>${m.label}</span></div>`).join('');$('#snapshot').innerHTML=`<div class="summary-row"><span>Online revenue</span><strong>${money(t.onlineRev)}</strong></div><div class="summary-row"><span>Offline revenue</span><strong>${money(t.offlineRev)}</strong></div><div class="summary-row"><span>Cost of goods</span><strong>${money(t.cogs)}</strong></div><div class="summary-row"><span>Expenses</span><strong>${money(t.expensesTotal)}</strong></div><div class="summary-row total"><span>Net profit</span><strong>${money(t.net)}</strong></div><p class="notice">${low+out} product(s) need stock attention.</p>`;$('#recentOrders').innerHTML=orderRows(t.orders.slice(0,7))}
function orderRows(os){if(!os.length)return '<div class="empty">No orders yet.</div>';return `<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>${os.map(o=>`<tr><td>${o.number}</td><td>${o.customer.name}</td><td>${money(o.total)}</td><td><span class="pill ${o.status==='Delivered'?'success':o.status==='Cancelled'?'danger':'warn'}">${o.status}</span></td><td><select class="select" onchange="updateOrder('${o.id}',this.value)">${['Pending','Confirmed','Processing','Shipped','Out for Delivery','Delivered','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`}
function updateOrder(id,status){const os=MS.get(MS.key.orders,[]),o=os.find(x=>x.id===id);if(!o)return;o.status=status;MS.set(MS.key.orders,os);MS.log(`Order ${o.number} changed to ${status}.`);MS.toast('Order updated.');renderAll()}
function renderProducts(){const ps=MS.get(MS.key.products,[]);$('#productsTable').innerHTML=`<table class="table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Cost</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${p.name}<br><small>${p.brand}</small></td><td>${p.category}</td><td>${money(p.price)}</td><td>${money(p.cost)}</td><td>${p.stock}</td><td><button class="small-btn" onclick="openProductForm('${p.id}')">Edit</button> <button class="small-btn" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')}</tbody></table>`}
function renderInventory(){const ps=MS.get(MS.key.products,[]);$('#inventoryTable').innerHTML=`<table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Threshold</th><th>Status</th></tr></thead><tbody>${ps.map(p=>`<tr><td>${p.name}</td><td>${p.stock}</td><td>${p.threshold}</td><td><span class="pill ${p.stock===0?'danger':p.stock<=p.threshold?'warn':'success'}">${p.stock===0?'Out of stock':p.stock<=p.threshold?'Low stock':'Healthy'}</span></td></tr>`).join('')}</tbody></table>`}
function renderOrders(){const os=MS.get(MS.key.orders,[]);$('#ordersTable').innerHTML=orderRows(os)}
function renderPOS(){const ps=MS.get(MS.key.products,[]);$('#posProduct').innerHTML=ps.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${p.name} — ${money(p.price)} (${p.stock} left)</option>`).join('');const os=MS.get(MS.key.offline,[]);$('#offlineTable').innerHTML=os.length?`<table class="table"><thead><tr><th>Product</th><th>Qty</th><th>Total</th><th>Date</th></tr></thead><tbody>${os.slice(0,10).map(o=>`<tr><td>${o.productName}</td><td>${o.qty}</td><td>${money(o.total)}</td><td>${MS.fmtDate(o.date)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No offline sales yet.</div>'}
function renderExpenses(){const es=MS.get(MS.key.expenses,[]);$('#expensesTable').innerHTML=es.length?`<table class="table"><thead><tr><th>Expense</th><th>Amount</th><th>Category</th><th>Date</th></tr></thead><tbody>${es.map(e=>`<tr><td>${e.name}</td><td>${money(e.amount)}</td><td>${e.category}</td><td>${MS.fmtDate(e.date)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No expenses recorded.</div>'}
function renderCustomers(){const os=MS.get(MS.key.orders,[]),map={};os.forEach(o=>{const k=o.customer.phone||o.customer.email||o.customer.name;map[k]??={...o.customer,count:0,total:0};map[k].count++;map[k].total+=o.total});const cs=Object.values(map);$('#customersTable').innerHTML=cs.length?`<table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Orders</th><th>Total spent</th></tr></thead><tbody>${cs.map(c=>`<tr><td>${c.name}</td><td>${c.phone||'-'}</td><td>${c.count}</td><td>${money(c.total)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Customers will appear after orders.</div>'}
function renderActivity(){const a=MS.get(MS.key.activities,[]);$('#activityTable').innerHTML=a.length?`<table class="table"><thead><tr><th>Activity</th><th>Date</th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.action}</td><td>${MS.fmtDate(x.date)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No activity yet.</div>'}
function renderSettings(){const s=MS.get(MS.key.settings,{});$('#setName').value=s.businessName||'';$('#setWa').value=s.whatsapp||'';$('#setDelivery').value=s.delivery||3000}
function renderAll(){renderOverview();renderProducts();renderInventory();renderOrders();renderPOS();renderExpenses();renderCustomers();renderActivity();renderSettings()}
function openProductForm(id){const m=$('#modal'),p=MS.get(MS.key.products,[]).find(x=>x.id===id);$('#editId').value=p?.id||'';$('#pfName').value=p?.name||'';$('#pfBrand').value=p?.brand||'';$('#pfCategory').value=p?.category||'Perfumes';$('#pfPrice').value=p?.price||'';$('#pfCost').value=p?.cost||'';$('#pfStock').value=p?.stock||'';$('#pfThreshold').value=p?.threshold||3;$('#pfRating').value=p?.rating||4.8;$('#pfImage').value=p?.image||'assets/images/marys-scent-flyer.jpeg';$('#pfDesc').value=p?.desc||'';m.classList.add('show')}
function closeProductForm(){$('#modal').classList.remove('show')}
$('#productForm').addEventListener('submit',e=>{e.preventDefault();const ps=MS.get(MS.key.products,[]),id=$('#editId').value||MS.id(),obj={id,name:$('#pfName').value,brand:$('#pfBrand').value,category:$('#pfCategory').value,price:Number($('#pfPrice').value),cost:Number($('#pfCost').value),stock:Number($('#pfStock').value),threshold:Number($('#pfThreshold').value),rating:Number($('#pfRating').value),image:$('#pfImage').value,desc:$('#pfDesc').value};const idx=ps.findIndex(p=>p.id===id);if(idx>=0)ps[idx]=obj;else ps.unshift(obj);MS.set(MS.key.products,ps);MS.log(`${idx>=0?'Updated':'Added'} product ${obj.name}.`);closeProductForm();MS.toast('Product saved.');renderAll()});
function deleteProduct(id){if(!confirm('Delete this product?'))return;const p=MS.get(MS.key.products,[]).find(x=>x.id===id);MS.set(MS.key.products,MS.get(MS.key.products,[]).filter(x=>x.id!==id));MS.log(`Deleted product ${p?.name||id}.`);renderAll()}
$('#posForm').addEventListener('submit',e=>{e.preventDefault();const ps=MS.get(MS.key.products,[]),id=$('#posProduct').value,p=ps.find(x=>x.id===id),qty=Number($('#posQty').value);if(!p||qty<1||qty>p.stock)return MS.toast('Check the selected stock quantity.');p.stock-=qty;MS.set(MS.key.products,ps);const sales=MS.get(MS.key.offline,[]);sales.unshift({id:MS.id(),productId:p.id,productName:p.name,qty,total:p.price*qty,cost:p.cost*qty,customer:$('#posCustomer').value,phone:$('#posPhone').value,payment:$('#posPayment').value,date:new Date().toISOString()});MS.set(MS.key.offline,sales);MS.log(`Offline sale: ${qty} × ${p.name}.`);e.target.reset();MS.toast('Offline sale recorded.');renderAll()});
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const es=MS.get(MS.key.expenses,[]),item={id:MS.id(),name:$('#expenseName').value,amount:Number($('#expenseAmount').value),category:$('#expenseCategory').value,payment:$('#expensePayment').value,description:$('#expenseDescription').value,date:new Date().toISOString()};es.unshift(item);MS.set(MS.key.expenses,es);MS.log(`Expense recorded: ${item.name} — ${money(item.amount)}.`);e.target.reset();MS.toast('Expense saved.');renderAll()});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();MS.set(MS.key.settings,{businessName:$('#setName').value,whatsapp:$('#setWa').value,delivery:Number($('#setDelivery').value)});MS.log('Business settings updated.');MS.toast('Settings saved.')});renderAll();
